<<<<<<< HEAD:echobin/app/layout.jsx
import { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
=======
>>>>>>> aa4bdaefac75a2831508847089aa8d8ae49f935b:echobin/app/layout.tsx

import Navbar from './bars/navbar';
import Footer from './bars/footer';
import './globals.css';

export const metadata = {
<<<<<<< HEAD:echobin/app/layout.jsx
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
=======
  title: 'EcoBin - Revolutionizing Waste Management',
  description: 'Join EcoBin in creating a greener future through sustainable waste management.',
};

export default function RootLayout({children}) {
>>>>>>> aa4bdaefac75a2831508847089aa8d8ae49f935b:echobin/app/layout.tsx
  return (
    <html lang="en">
      <body>
        <Navbar />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
